### ISSUE TITLE
[vsync_opengl_swc_init ERROR] Failed to load a swap control extension

### ISSUE THREAD

**Issue by geekofChangPing** [chjj/compton#566]
Platform:raspberry pi 4b + archlinuxarm

GPU, drivers, and screen setup: GPU：broadcom VideoCore VI
                                                     Drivers：xf86-video-fbdev
 
When I try to start compton I get :
```
[vsync_opengl_swc_init ERROR] Failed to load a swap control extension
[session_init FATAL ERROR] Failed to initialize the backend

```
I just wonder if compton support this kind of drivers now.

**Comment by ghost** [comment]
I just got the same error in VirtualBox running ArcoLinux i3. My login screen is black with high contrast, yet my Bspwm installation in the same vm works like a charm. Running VBoxSVGA no 3D to get correct resolution. Just starting my search, and I'm a noob roughly.

**Comment by ecesar88** [comment]
Same error here, started some days ago. I already updated it and it still persists...

**Comment by logannance** [comment]
Same, using VirtualBox Artix Linux bspwm. I guess it just can't utilize the drivers on our systems?

**Comment by ecesar88** [comment]
My problem is that i was using nvidia-dkms to run the linux-zen kernel. Switching back to normal nvidia drivers did the trick. But it'll not work with nvidia-dkms...

**Comment by coolapso** [comment]
seeing the same issue, 

```
$picom -b
[ 12/28/2020 18:58:26.345 vsync_opengl_swc_init ERROR ] Failed to load a swap control extension.
[ 12/28/2020 18:58:26.345 session_init FATAL ERROR ] Failed to initialize the backend
```
```
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.9.14-arch1-1
 Uptime: 26m
 Packages: 1917
 Shell: bash 5.1.4
 Resolution: 4800x4720
 WM: i3
 GTK Theme: Arc-Dark [GTK2/3]
 Disk: 334G / 474G (75%)
 CPU: AMD Ryzen 7 2700X Eight-Core @ 16x 3.7GHz
 GPU: GeForce RTX 2080
 RAM: 3862MiB / 32125MiB
 NVIDIA Driver Version: 455.45.01

```

**Comment by coolapso** [comment]
For those who might stumble here, 

My case was solved by loading nvidia kernel modules at boot: https://wiki.archlinux.org/index.php/NVIDIA#DRM_kernel_mode_setting

Might be worth to look at: https://bbs.archlinux.org/viewtopic.php?id=257769

This is arch documentation, but more often than not it is useful for other distros.

**Comment by YuryiM** [comment]
Hi 4s3ti, can you post what you added to your grub parameters (if you used grub)? I added `nvidia-drm.modeset=1` to /etc/default/grub so it looks like this:
`GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash nvidia-drm.modeset=1`"

I have also tried adding that parameter to the grub menu at boot but that also doesn't seem to work, I still get the exact same error with picom.

**Comment by coolapso** [comment]
As per the documentation above, there are 2 options, the easiest one which is to add the parameter on grub, and for that make sure you follow all the steps at: https://wiki.archlinux.org/index.php/Kernel_parameters#GRUB

The second option which is a bit more complex, but loads the modules earlier, is to add `MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)` to `/etc/mkinitcpio.conf` following the procedures at: https://wiki.archlinux.org/index.php/Mkinitcpio#Manual_generation

either way any of the options worked well for me ... and i am currently loading it with grub to avoid having the pacman hook on arch linux: 

`GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet nvidia-drm.modeset=1"`

Please read carefully all the documentation, i take no responsibility for any wrong-doing or any issues that may happen
